### ISSUE TITLE
Windows: run mongodb as a user controlled background process

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#235]
- [ ] How to run in python on windows a background process without administrative priviledges
- [ ] implement a solution that does not kill the process when the terminal is killed in which the process was generated. Thisis the equivalent of the "&" in a python shell, but we need to do this from python

**Comment by Vafa-Andalibi** [comment]
This is already implemented in 13f1ed7a3ad721324c3b610fce210c22151eab07

**Comment by laszewsk** [comment]
as it turns out this does not work as the documentation on how to install mongodb on the system is not working or incorrect.

cms admin mongo install --force on windows

has some strange behavior it does not install in the instalation path but just under 

~/.cloudmesh/mongodb

I set therefore in configuration that as the path 

but than wehne we start from taht dir mongo can not be started.

we have at this time NO information on how to install mongo properly on a machine, also system path need sto be set and there is also not documentation for that

am i looking at the wrong thing

i made mods as also the install program was not working at all

**Comment by Vafa-Andalibi** [comment]
I think this issue is not related to that because this is basically related to whether mongo is running as user process or not. The truth of the matter is that "if" mongo is installed correctly, it will run as a user controller process. 
This issue of wrong installation is because of the bug at c540419bb912f225f84a06be0f04e7baa33691f5 for wrong usage of mongo_path which means it either was not tested, or the implementer expected that. 

I've fixed this anyways. I'll push it soon

**Comment by Vafa-Andalibi** [comment]
fixed in dd6b36bc2a633835763258e136011632b9de6321

**Comment by laszewsk** [comment]
Urgently give me a call

Now nothing is running anymore

**Comment by Vafa-Andalibi** [comment]
For the record, `cms init` and all variations of `cms admin mongo` were tested on windows.

**Comment by laszewsk** [comment]
cms init was tested on openstack.

 modifications were made as the keyupload was not working in cms init.
